### ISSUE TITLE
State of development?

### ISSUE THREAD

**Issue by lunelson** [soulcutter/husler#4]
Hey, just found this from the HUSL page; I too would love to see this packaged in to a Compass extension but I'm wondering how complete it is. From the HUSL page it says it's only started but your readme doesn't indicate that it's un-ready at all. 

Is it ready to go?

thx

**Comment by soulcutter** [comment]
It's functional - if you run into any issues or have any questions about this implementation just let me know.

**Comment by lunelson** [comment]
Thanks. I'm going to see if I can wrap it up as a Compass extension gem for Sass functions. I'll post the link when I get a repo up...

**Comment by lunelson** [comment]
OK. No luck with Compass so far, but I've got it working in SassScript. Problem is, the numbers aren't coming out right. The following should produce something with a hue of 240 (blue); but it's significantly leaning towards green:

``` ruby
Husler.husl_to_rgb(240,100,50).map {|c|c*255}
 => [0.005002177000229003, 126.31835463505367, 182.92943962461564] 
```

In fact if I create the color and then retrieve the hue (using Sass' built in `hue()` function), I'm only getting `198.46154deg` which is definitely not right. Any ideas?

**Comment by boronine** [comment]
@lunelson reached out to me by email, I'm going to reply here.

First of all, thanks for your work! I'm really excited to see a Ruby port, particularly for the sake of Sass and Compass.

As of now it seems that this port is broken. It shouldn't be too hard to debug it as HUSL consists entirely of pure functions. I just updated the testing code for the original CoffeeScript implementation, now it generated a much more useful snapshot. You can find the current snapshot here: https://github.com/boronine/husl/blob/master/test/snapshot-2.x.x.json

The format is as follows:

```
{
  "#000000": {
    rgb: [ 0, 0, 0 ],
    xyz: [ 0, 0, 0 ],
    luv: [ 0, 0, 0 ],
    lch: [ 0, 0, 0 ],
    husl: [ 0, 0, 0 ],
    huslp: [ 0, 0, 0 ]
  },
  ...
}
```

You can start by testing hex->rgb, then once that passes, go to hex->rgb->xyz etc. For my tests, I'm using a fairly low error tolerance (0.00000001), you could increase it if Ruby's floating point behavior differs somehow.

One suggestion: the current Ruby implementation mutates the tuple before returning it, I would highly recommend returning a new tuple to make the functions pure.

Looking forward to announcing this port on the project page. Let me know if you have any questions.

**Comment by lunelson** [comment]
I've just related these findings to @boronine but i'll mention it here: HSL and HUSL do not seem to correspond on hue or saturation values based on what I can see from picking colors on the HUSL page; so this discrepancy may originate with the original code.

Taking the HSL and HUSL color range illustrations from the original page and lining them up vertically, it's clear to see the hue values do not correspond, e.g. with blue or yellow, they are not in the same line, and I've confirmed this by picking colors and analyzing them after the fact, that the stated rgb and hsl values are not the same as the color being produced.

I'm wondering if it's due to whitepoint correction, but not sure if that could explain it.

![hsl-vs-husl](https://f.cloud.github.com/assets/1242864/424799/c169b44c-ad97-11e2-975b-491225dae344.jpg)

**Comment by lunelson** [comment]
Incidentally the same discrepancy in hue alignment can be seen between the HCL and HSL examples on this page, which is doing a similar color transformation, so perhaps there's something about all the color-space translations that's causing hue to shift:

http://cscheid.net/blog/hcl_color_space_blues

**Comment by boronine** [comment]
The hue isn't supposed to match HSL. HSL's hue isn't uniform, whereas HUSL's is. HUSL's hue component corresponds exactly to CIE LCHuv hue component, which is a result of experiments on human vision. HSL's hue component is just a clever geometric transformation: note how narrow yellow is, for example, compared to blue.

I mention it briefly on the HUSL page and also in more detail here: http://boronine.com/2012/03/26/Color-Spaces-for-Human-Beings/

Also note that apart from the snapshot I provided, you can play around with HUSL if you open the JavaScript console on HUSL's homepage. You can access all the conversion functions as defined in https://github.com/boronine/husl/blob/master/husl.coffee in `$.husl._conv`

**Comment by lunelson** [comment]
Ah, I see. But the hue values of HSL are also the basis of the RGB color wheel. When viewed on a wheel one sees how R (0,360), G (120), and B (240) balance one another, and how Cyan, Magenta and Yellow lie between them. People who work with color on a computer know this color wheel like the back of their hands and know how to specify colors by number in HSL. It's just the "Lightness" aspect of HSL that's always been a bit meaningless as far as true "lightness" goes. HUSL the way you described it, sounded like it would be a perceptual-brightness-conformed version of HSL and therefore a tool that anyone who knows color could pick up and use; but if it uses a different hue distribution than HSL it's not going to be easy to use at all, and the name maybe a bit misleading. Furthermore, it doesn't change the fact that the values your color picker is showing simply aren't correct. 

Here's another screenshot as an example; I picked a random color then sampled it with [Spectrum](http://www.eigenlogik.com/spectrum/). You can see the RGB of what was actually produced is not what your picker is reporting. It looks like the picker is reporting the numbers as if it was an HSL spread, while producing a color from a HUSL spread.

![image](https://f.cloud.github.com/assets/1242864/427045/e62c499c-add9-11e2-8cc8-bfcb8ed694d5.png)

**Comment by boronine** [comment]
1. The H, S and L reported by my color picker are HUSL's components, not HSL's. I realize it might be a little confusing. The RGB components reported by your color inspector (138, 118, 1) correspond to #8A7601, a darker color than the one shown by the picker. Could you try to verify that again? If you get the same result, it must be something to do with color profiles, which I don't know much about.
2. Regarding your color wheel comments. HUSL and HSL are completely different color spaces. HUSL is not a modification of HSL. It is derived from CIE LCh(uv), as I describe on its homepage. An HSL color wheel is a reflection of the HSL color space, you cannot use it to work with HUSL. You _could_, however, make a HUSL color wheel similarly to how I made that color picker.
3. While many designers have grown very familiar with the kind of RGB sliders you have in the screenshot above, they have little to do with how humans actually perceive color and more to do with our display technology.

When I was researching color a year ago, it took me quite a while before all this stuff "clicked". I may be wrong, but it sounds like you don't have a clear understanding of how humans see color, which is a prerequisite to understanding color spaces. I am no color scientist, but perhaps I could help you. Let me know if my blog post doesn't make sense to you, I could try to clarify it.

**Comment by lunelson** [comment]
OK @boronine, well then I understand your explanation but I think we're approaching this from different directions. 

For the record, I'm familiar with the concept of color spaces, and I recently learned about CIE-LChUV (also called HCL), and it's unique ability to modify lightness without shifting hue (unlinke Lab, Luv, YUV or YCbCr), and this was the thing I was interested in. It's illustrated very well in the WebGL color picker at the link I posted above "HCL color space blues". So I understood this before I came across your HUSL project, as well as the problem of its discontinuity of chroma vs lightness; only I hadn't noticed that HCL or CIELChUV also has—maybe as a result of the various transformations, or because it reflects the sensitivities of human vision more closely, I don't know—a different and seemingly irregular hue distribution, compared to the strictly regular distribution of RGB/HSL.

So while I appreciate and understand that HCL's distributions are more accurate wrt human vision, I am saying that I think a color system which is to be used programmatically (specifying colors by number, as we would use it in Sass), should be consistent and regular in terms of the mental model by which colors are _used_, not necessarily the physics of how they are perceived, and that HUSL's mismatch with HSL in this respect is problematic.

To put it another way: it's great that HUSL deals with the discontinuity of chroma vs. lightness in HCL, but unless it can also conform its hue distribution to the standard hue distribution of digital (RGB) color, the H numbers have no known meaning for people who want to use it directly in a coding context, and the only way to work with it is visually, by using a picker, such as the one you made, or a "wheel" type. This is a bummer, because in my experience, front end devs—especially those using Sass, Stylus or LESS—don't turn to a color picker every time they need a color: they know with HSL that green is 120, they know that fuchsia is 300, etc. One can guesstimate colors because the H component alone gets you to the right hue (conceptually, _the color_), and then you can adjust S (how much) and L (how light, how dark) as you see fit.

Now, I would still _really_ like to have a perceptually-uniform-brightness version of HSL, because the L value in HSL only tints or shades a given color (defined by H and S) and does not reflect anything about how truly bright or dark a color ultimately is (this is the original problem); but I don't think you can take away the color wheel as a reference for hues, and if I'm understanding correctly that HUSL is as you say "completely different" from HSL, and they have actually hardly anything in common, then I think calling it "human-friendly HSL" is misleading, and it would have been more accurate to call it "HUCL: human-friendly HCL or CIE-LChUV", so people would understand that their previous reference points do not apply.

Anyway, all that being said, 2 things:
1. the program I used to sample the color in my post above was indeed wrong. I'm not sure how, perhaps it's a Display profile problem. I sampled colors from your picker today with a different program and your RGB values check out. Sorry for this.
2. is the "error", therefore, that I was getting with Husler above not actually an error, but just my misunderstanding of HUSL hue? Are the calculations of this ruby port consistent with your original JS version? I'd really like to know because I think I could still use Husler to create the thing I'm after, I just have to juggle around a bit more so I can specify hues the way I know them...

Thanks for all your input and clarifications,

L

**Comment by lunelson** [comment]
Addition: WRT "regularity" of hue – I see your point and I can see that visually, transitions in the HUSL Spectrum seem more even and in a sense this could be thought of as "regular"; but I'm talking about the numerically regular distribution of color across 360 degrees, i.e. red 0, yellow 60, green 120, cyan 180, blue 240, magenta 300, which I rely on mentally if I have to type out a color by numbers. However I'd be very interested to see what HUSL looks like distributed on a wheel, and what one gets with standard color schemes such as complementary, split-complementary, triad, etc., when applied on that distribution ;)

**Comment by boronine** [comment]
1. I don't think "human-friendly HSL" is misleading. HUSL defines hue, saturation and lightness, the same components as HSL. These components have the same semantics as the corresponding HSL components. HUSL and HSL share the same gamut. However, HUSL is a _different_ color space. One that, unlike HSL, is tuned for perceptual uniformity. All of this should be very clear just from reading the introductory section on HUSL's homepage and looking at the comparison table. As for hue uniformity, it is mentioned in the comparison table, as well as in its own section on the homepage. I don't see how anyone who has skimmed the homepage would expect HUSL's hue component to match HSL's.
2. The color space that you describe, a modified HSL with a fixed lightness component, is not a bad idea at all. In fact, I think it would be quite useful. However, this color space is simply _not_ HUSL. HUSL's main design goal is perceptual uniformity. Trying to look like HSL is the opposite of that.
3. Regarding complementary, triad etc., I would love to see that too. I haven't made a HUSL color wheel so I don't know how well it would work in comparison with the RGB color wheel. I _have_ used HUSL to generate color palettes which look pretty nice: http://boronine.com/husl/syntax/
4. Regarding this port, I haven't tested it myself, so I don't know whether it's correct or not. To verify its correctness, it needs to be tested against a snapshot of the canonical CoffeeScript version. I describe how to do it here: https://github.com/soulcutter/husler/issues/4#issuecomment-16978452 You may skip the intermediate steps and test hex->HUSL directly. If it works, it can be assumed that the intermediate steps are also correct.

**Comment by boronine** [comment]
The old snapshot, one that has already been integrated into this repo, is still relevant. I made the new one specifically to ease debugging. So if you can verify husler against the old snapshot, you don't have to use the new one.
